apiVersion: v1
kind: ConfigMap
metadata:
  name: db-connection
data:
  host: mysql
  name: wpdb
  bind-address: 0.0.0.0
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
  password: NjU0MzIxQEJk # (echo -n '654321@Bd' | base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials 
data:
  username: d3B1c2Vy     # (echo -n 'wpuser' | base64)
  password: NDMyMTEzQEJk # (echo -n '432113@Bd' | base64)