kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    bind-address			        = 0.0.0.0
    character-set-server=utf8
    collation-server=utf8_bin
    pid-file			            = /var/run/mysqld/mysqld.pid
    socket			      	        = /var/run/mysqld/mysqld.sock
    datadir			      	        = /var/lib/mysql
    secure-file-priv	    	    = NULL
    default-authentication-plugin 	= mysql_native_password
    general_log 			        = 1
    general_log_file 		        = /var/lib/mysql/general.log
    !includedir /etc/mysql/conf.d
