kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  default.conf: |
        server {
            charset utf-8;
            client_max_body_size 128M;
            listen 80;
            server_name _;
            root /var/www/html;
            index index.php index.html;
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Content-Type-Options "nosniff";
            location = /favicon.ico { access_log off; log_not_found off; }
            location = /robots.txt  { access_log off; log_not_found off; }
            location / {
                try_files $uri $uri/ =404 /index.php?$query_string;
            }
            location /nginx_status {
                stub_status on;
                access_log on;
                allow 127.0.0.1;
                deny all;
            }
            location ~ \.php$ {
                fastcgi_pass 127.0.0.1:9000;
                try_files $uri /index.php =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
                fastcgi_busy_buffers_size 512k;
                fastcgi_buffer_size 512k;
                fastcgi_buffers 16 512k;
            }
            location ~* .(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
                expires max;
                log_not_found off;
                access_log off;
            }
            location ~ /\.(?!well-known).* {
                deny all;
            }
        }
