apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv-storage-wordpress
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/www/html"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
spec:
  storageClassName: pv-storage-wordpress
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi