kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarqube-local-pv
  labels:
    type: local
    app: sonar
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-sonarqube
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/sonarqube"