kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-local-pv
  labels:
    type: local
    app: postgres
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-postgresql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/postgresql"
