apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sonar
  labels:
    app: postgres
    tier: database
spec:
  selector:
    matchLabels:
      app: postgres
      tier: database
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: postgres
          env:
          - name: POSTGRES_USER 
            valueFrom:
              secretKeyRef:
                name: postgres-db-secret-config
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-db-secret-config
                key: passwd
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-db-secret-config
                key: database

          volumeMounts:
          - name: postgredb
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgresql-local-pvc
